music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/<album_id>/
    # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #  # /music/<album_id>/favorite
    # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

myfirstproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=100)

    def __str__(self):
        return self.album_title + ' - '+self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default= False)

    def __str__(self):
        return self.song_title

music/views.py
# from django.shortcuts import render, get_object_or_404
# from .models import Album, Song
#
#
# def index(request):
#     all_albums = Album.objects.all()
#     return render(request, 'music/index.html', {"all_albums": all_albums})
#
#
# def detail(request, album_id):
#
#     # Detailed way to get an object or throw 404 error is object not present
#     # Writing here for revision
#
#     # try:
#     #     album = Album.objects.get(pk=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Album does not exist")
#
#     # This block of code does exactly what is done above by try except statement
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {"album": album})
#
#
# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except(KeyError, Song.DoesNotExist):
#         return render(request, 'music/detail.html', {
#             "album": album,
#             "error_message": "You have not selected a valid song "
#         })
#     else:
#         selected_song.is_favourite = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {"album": album})



###############################################################################################################################################################
###############################################################################################################################################################

# This is the new way we are going to create views using generic view pattern

from django.views import generic
from .models import Album, Song


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Samaira Music {% endblock %}</title>
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" >
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" ></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Samaira Music</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="">
                    <a href=href="{% url 'music:index' %}>
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href=href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp
                        Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href=href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp
                        Add Album
                    </a>
                </li>
                <li class="">
                    <a href=href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

<!-- This is again the old way we used to handle the details page in case -->

{% comment %} {% block title %} Album Details {% endblock %}

{% block body %}
    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>


    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'music:favorite' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}
                 {% if song.is_favourite %}
                    <img src="http://i.imgur.com/b9b13Rd.png"/>
                 {% endif %}
            </label><br>
        {% endfor %}
        <input type="submit" value="Favourite">
    </form>
{% endblock %}{% endcomment %}



<!-- Below is the new way we structure our form, which is a lot less code -->


{% block title %} Album Details {% endblock %}

{% block body %}
    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>

        {% for song in album.song_set.all %}
                {{ song.song_title }}
                 {% if song.is_favourite %}
                    <img src="http://i.imgur.com/b9b13Rd.png"/>
                 {% endif %}
                 <br>
        {% endfor %}

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

<!-- This is the piece of code we used to use when we use functions in our views .
     We can do this in more cleaner way using below -->

{% comment %}{% block body %}
{% if all_albums %}
    <h3> Here are all my albums</h3>
    <ul>
         {% for album in all_albums %}
             <li><a href="{% url 'music:detail'  album.id %}"> {{ album.album_title }}</a></li>
         {% endfor %}
    </ul>
 {% else %}
    <h3> No Album present</h3>
 {% endif %}
{% endblock %}{% endcomment %}


{% block body %}

        <ul>
             {% for album in all_albums %}
                 <li><a href="{% url 'music:detail'  album.id %}"> {{ album.album_title }}</a></li>
             {% endfor %}
        </ul>

{% endblock %}